# This file was generated by GoReleaser. DO NOT EDIT.
cask "goji" do
  name "goji"
  desc "Commitizen-like Emoji Commit Tool written in Go"
  homepage "https://github.com/muandane/goji"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goji"
  manpage "manpages/goji.1.gz"
  bash_completion "completions/goji.bash"
  zsh_completion "completions/goji.zsh"
  fish_completion "completions/goji.fish"
  depends_on formula: [
      "git",
    ]

  on_macos do
    url "https://github.com/muandane/goji/releases/download/v#{version}/goji_v#{version}_Darwin_all.tar.gz"
    sha256 "73e236171c0dbca10cd5f0b368f57bf2b4ee92cb13def5677cd223c8a924bcac"
  end

  on_linux do
    on_intel do
      url "https://github.com/muandane/goji/releases/download/v#{version}/goji_v#{version}_Linux_x86_64.tar.gz"
      sha256 "6abe1a32b7943a833ae4b126335c6d2845ec93b573bcdda1ac534b7f839384b5"
    end
    on_arm do
      url "https://github.com/muandane/goji/releases/download/v#{version}/goji_v#{version}_Linux_arm64.tar.gz"
      sha256 "7ad244f1884b87fe4155e6bf34e2c7decdcd9d787005355117e1450ff1d51bb6"
    end
  end

  # No zap stanza required
end
