# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcost < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-tap"
  version "0.0.2"

  on_macos do
    url "https://github.com/muandane/cloudcost/releases/download/v0.0.2/cloudcost_0.0.2_Darwin_all.tar.gz"
    sha256 "f9588f2ed64803de5429d42bd4051ec8cf81169bdc1f7f171adca0d86c78184d"

    def install
      bin.install "cloudcost"
      bash_completion.install "completions/cloudcost.bash" => "cloudcost"
      zsh_completion.install "completions/cloudcost.zsh" => "_cloudcost"
      fish_completion.install "completions/cloudcost.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/cloudcost/releases/download/v0.0.2/cloudcost_0.0.2_Linux_arm64.tar.gz"
      sha256 "83d48a1b87334338d85789acc4ad5926c73569de05d50a5511bafe463ddad6e8"

      def install
        bin.install "cloudcost"
        bash_completion.install "completions/cloudcost.bash" => "cloudcost"
        zsh_completion.install "completions/cloudcost.zsh" => "_cloudcost"
        fish_completion.install "completions/cloudcost.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/cloudcost/releases/download/v0.0.2/cloudcost_0.0.2_Linux_x86_64.tar.gz"
      sha256 "78fde8845ff5ec6f47924209bf6d485f28b23e4bfd51f3c93f6c289390feb2d8"

      def install
        bin.install "cloudcost"
        bash_completion.install "completions/cloudcost.bash" => "cloudcost"
        zsh_completion.install "completions/cloudcost.zsh" => "_cloudcost"
        fish_completion.install "completions/cloudcost.fish"
      end
    end
  end
end
