# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcost < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-tap"
  version "0.0.2"

  on_macos do
    url "https://github.com/muandane/cloudcost/releases/download/v0.0.2/cloudcost_0.0.2_Darwin_all.tar.gz"
    sha256 "a3bca78351ff4951b173c01f964e28efe24a8fbcb5035f352b553ae1ea648669"

    def install
      bin.install "cloudcost"
      bash_completion.install "completions/goji.bash" => "goji"
      zsh_completion.install "completions/goji.zsh" => "_goji"
      fish_completion.install "completions/goji.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/cloudcost/releases/download/v0.0.2/cloudcost_0.0.2_Linux_arm64.tar.gz"
      sha256 "d8c445196da4b5156ab0a08b773e7c14f0391a3390f2b8ad294dfabee892a1be"

      def install
        bin.install "cloudcost"
        bash_completion.install "completions/goji.bash" => "goji"
        zsh_completion.install "completions/goji.zsh" => "_goji"
        fish_completion.install "completions/goji.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/cloudcost/releases/download/v0.0.2/cloudcost_0.0.2_Linux_x86_64.tar.gz"
      sha256 "fb9f45e8c99b162ced0751950215330964137e8c0d287185669f8530317af84c"

      def install
        bin.install "cloudcost"
        bash_completion.install "completions/goji.bash" => "goji"
        zsh_completion.install "completions/goji.zsh" => "_goji"
        fish_completion.install "completions/goji.fish"
      end
    end
  end
end
