# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-muandane"
  version "0.0.2-rc1"

  depends_on "git"

  on_macos do
    url "https://github.com/muandane/goji/archive/refs/tags/v0.0.2-rc1.tar.gz"
    sha256 "b47dc0e745a1601bcc07536339411891831b58700f733acf7d88a4c86a4cbdbf"

    def install
      bin.install "goji"
      bash_completion.install "completions/goji.bash" => "goji"
      zsh_completion.install "completions/goji.zsh" => "_goji"
      fish_completion.install "completions/goji.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc8/goji_Linux_arm64.tar.gz"
      sha256 "9e5a56a621896b5ab50b4ef23a65a06e7fac9a68766ef9dcb7df3a862555b46f"

      def install
        bin.install "goji"
        bash_completion.install "completions/goji.bash" => "goji"
        zsh_completion.install "completions/goji.zsh" => "_goji"
        fish_completion.install "completions/goji.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc8/goji_Linux_x86_64.tar.gz"
      sha256 "414eab2550d2472e4226af6428b1c9189c40033dd8de88788afac557f21245a6"

      def install
        bin.install "goji"
        bash_completion.install "completions/goji.bash" => "goji"
        zsh_completion.install "completions/goji.zsh" => "_goji"
        fish_completion.install "completions/goji.fish"
      end
    end
  end
end
