# This file was generated by GoReleaser. DO NOT EDIT.
cask "goji" do
  name "goji"
  desc "Commitizen-like Emoji Commit Tool written in Go"
  homepage "https://github.com/muandane/homebrew-tap"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goji"
  depends_on formula: [
      "git",
    ]

  on_macos do
    url "https://github.com/muandane/goji/releases/download/v#{version}/goji_v#{version}_Darwin_all.tar.gz"
    sha256 "0e21cc14f8b9f98fe3795abafceeaf82c307ebb24cfb7724911273009586ecac"
  end

  on_linux do
    on_intel do
      url "https://github.com/muandane/goji/releases/download/v#{version}/goji_v#{version}_Linux_x86_64.tar.gz"
      sha256 "8ce76544c6d5c1e50bbcbf119a9403db364425dc6e41e68e64d93560d9e3bbcb"
    end
    on_arm do
      url "https://github.com/muandane/goji/releases/download/v#{version}/goji_v#{version}_Linux_arm64.tar.gz"
      sha256 "77b39520c5fc56434c25a463fd545b3498829edb4768ed04955937394f7d1fb3"
    end
  end

  postflight do
    bash_completion.install "completions/goji.bash" => "goji"
    zsh_completion.install "completions/goji.zsh" => "_goji"
    fish_completion.install "completions/goji.fish"
    man1.install "manpages/goji.1.gz"
  end

  # No zap stanza required
end
